name: Build-Master

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build GuaranteedRate.Sextant\GuaranteedRate.Sextant.csproj --configuration Release --no-restore
    - name: nuget push
      run: dotnet nuget push GuaranteedRate.Sextant\bin\release\*.nupkg -s https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json -k ${{ secrets.GITHUB_TOKEN }} --skip-duplicate --no-symbols
